advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(),name='index'),
    path('basicapp/', include('basicapp.urls',namespace='basicapp')),
]

advcbv/basicapp/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

# path('<slug:pk>/')

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/',views.SchoolDetailView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete'),

]

advcbv/basicapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=260)
    principal = models.CharField(max_length=260)
    location = models.CharField(max_length=260)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advcbv/basicapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from . import models
# Create your views here.

# class CBView(View):
#     def get(self,request):
#         return HttpResponse('Class based View')

class IndexView(TemplateView):
    template_name = 'index.html'
#
#     def get_context_data(self,**kwargs):
#         context = super().get_context_data(**kwargs)
#         context['injectme'] = '''BASIC INJECTION
#          def get_context_data(self,**kwargs):
#              context = super().get_context_data(**kwargs)
#             context['injectme'] = 'BASIC INJECTION'
#             return context'''
#         return context


class SchoolListView(ListView):
    # or u can use context to define variable manually
    context_object_name = 'schools'
    model = models.School
    template_name = 'basicapp/schoollist.html'

    # models.school retruns school_list

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basicapp/schooldetail.html'

class SchoolCreateView(CreateView):
    fields = '__all__'
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basicapp:list')

advcbv/basicapp/templates/basicapp/basicappbase.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BASE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item"><a class="nav-link active" href="{% url 'admin:index' %}">Admin</a></li>
        <li class="nav-item"><a class="nav-link active" href="{% url 'basicapp:create' %}">Create</a></li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
</nav>
  <div class="container">
    <div class="jumbotron">
      {% block body_block %}
      {% endblock %}
    </div>
  </div>
  </body>
</html>

advcbv/basicapp/templates/basicapp/school_confirm_delete.html
<!DOCTYPE html>
    <title></title>
    {% extends "basicapp/basicappbase.html" %}
    {% block body_block %}
    <h1>Delete {{ school.name }}?</h1>
    <form method="POST">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
    </form>
    {% endblock %}

advcbv/basicapp/templates/basicapp/school_form.html
<!DOCTYPE html>
    <title></title>
    {% extends "basicapp/basicappbase.html" %}
    {% block body_block %}
    <div class="jumbotron">
      <h1>
        {% if not form.instance.pk %}
        Create School
        {% else %}
        Update School
        {% endif %}
      </h1>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">

      </form>
    </div>
    {% endblock %}

advcbv/basicapp/templates/basicapp/schooldetail.html
{% extends "basicapp/basicappbase.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to Details of all Schools</h1>
  <h2>School Details:</h2>
  <p>Name: {{ school_detail.name }}</p>
  <p>Principal: {{ school_detail.principal }}</p>
  <p>Location: {{ school_detail.location }}</p>
  <h3>Students:</h3>
  {% for stud in school_detail.students.all %}
  <p>{{ stud.name }} who is {{ stud.age }} years old</p>
  {% endfor %}
</div>
<div class="container">
  <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update Here</a>
  <a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>
</div>
{% endblock %}

advcbv/basicapp/templates/basicapp/schoollist.html
{% extends "basicapp/basicappbase.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to list of all Schools</h1>
  <ol>
    {% for school in schools %}
    <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
    {% endfor %}
  </ol>
</div>
{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BASE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'basicapp:list' %}">School</a>
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li><a class="nav-link active" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a class="nav-link active" href="{% url 'basicapp:create' %}">Create</a></li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
</nav>
  <div class="container">
    <div class="jumbotron">
      {% block body_block %}
      {% endblock %}
    </div>
  </div>
  </body>
</html>

advcbv/templates/index.html
<!DOCTYPE html>
    <title></title>
    {% extends "base.html" %}
    {% block body_block %}
      <div class="jumbotron">
        <h1>Hi Home Page</h1>
      </div>
    </div>
    {% endblock %}